### ISSUE TITLE
<main> sementic

### ISSUE THREAD

**Issue by Malix-Off** [ahqsoftwares/tictactoe#8]
https://github.com/ahqsoftwares/tictactoe/blob/c236260754b770f6daa821af2d691a93efea9ad9/index.html#L23

need to be changed to

```html
<main></main>
```

And every reference of it be fixed accordingly

**Comment by ahqsoftwares** [comment]
The react renders this portion on load. This is the react root, must reference an id

**Comment by Malix-Off** [comment]
I think it would really be possible to reference an html element link instead of an html ID
